### ISSUE TITLE
media content and enclosures

### ISSUE THREAD

**Issue by yavuz** [DigitalLeaves/SwiftFeedParser#1]
hi
thank you so much for app.
but;
<media content> and <enclosures> I could not find how I get. am I missing something?

for example;
enclosure tag => http://feeds.feedburner.com/TheAustralianNewsNDM
media tag => http://d.yimg.com/au.rss.news.yahoo.com/thewest/wa.xml

**Comment by DigitalLeaves** [comment]
Hi Yavuz,

Thank you for your collaboration! Unfortunately, the length of the enclosures is supposed to be a Int (it's a lenght, isn't it?) so it can't be a String object, I cannot accept this as a fix. I don't know how could you get a feed in which the length is not properly retrieved, but I suspect maybe it's because it's not well formed. 

Im travelling right now, but will arrive home tomorrow, give me some time and I will try to look at the problem. Thank you again!
Best regards.

Nacho.

---

Digital Leaves
Creative software development

http://digitalleaves.com

**Comment by yavuz** [comment]
You're right about Int. My fault. I think that can not be integer values return first. I did this for it.

I sent changing again. if you still can not accept not appropriate. no problem :) good work.

https://github.com/DigitalLeaves/SwiftFeedParser/pull/3

**Comment by DigitalLeaves** [comment]
Hi Yavuz. Checked it and it's properly working now, as an In (which is required later for retrieving the media). Thank you so very much for your collaboration, you are a great developer.
